### ISSUE TITLE
PyPI has 0.2.0 release (with regressions?) but there is no such git tag

### ISSUE THREAD

**Issue by danc86** [simoncozens/vharfbuzz#12]
I was using the vharfbuzz 0.2.0 release as published on PyPI. I realised it seems to be missing this fix:

https://github.com/simoncozens/vharfbuzz/commit/2693238e403829a2c2d94b31d0bc4663799da91e

Then I realised there is no git tag for v0.2.0, nor any history in this repo past July 2022. The upload on PyPI is dated 4 March 2023. Did the v0.2.0 release come from somewhere else? Did it (accidentally) regress?

**Comment by simoncozens** [comment]
No, I just forgot to push some stuff; I've done that now!

**Comment by danc86** [comment]
Oh I see, I was using an older uharfbuzz which is why the vharfbuzz 0.2.0 release wasn't working. Thanks.
