### ISSUE TITLE
AttributeError: 'uharfbuzz._harfbuzz.Font' object has no attribute 'get_var_coords_design

### ISSUE THREAD

**Issue by MikeUdin** [simoncozens/vharfbuzz#20]
There an error while applying variable font axes. 
` File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/vharfbuzz/__init__.py", line 145, in shape
    self._saved_variations = hbfont.get_var_coords_design()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'uharfbuzz._harfbuzz.Font' object has no attribute 'get_var_coords_design'`

**Comment by simoncozens** [comment]
I'm guessing the answer is "upgrade your uharfbuzz" since this was introduced in v0.37.3, but we should also fix the dependency in requirements.

**Comment by dscorbett** [comment]
The fix was reverted in 89ad8ea34fd4fc0b3b7e667652c406ddc82be5c4, so this issue should be reopened or refixed.
