### ISSUE TITLE
Use SVGPathPen instead?

### ISSUE THREAD

**Issue by madig** [simoncozens/vharfbuzz#8]
This:

https://github.com/simoncozens/vharfbuzz/blob/888916e7f77fecb7b520eee46f022ae92be983d5/lib/vharfbuzz/__init__.py#L251

could maybe be replaced by:

```py
        pen = fontTools.pens.svgPathPen.SVGPathPen(None)
        self.hbfont.draw_glyph_with_pen(info.codepoint, pen)
        glyph_path = pen.getCommands()
```

Then you could remove a bunch of functions?

**Comment by simoncozens** [comment]
Maybe, yes. We should benchmark it. In general I'm not a fan of replacing C with Python. ;-)

**Comment by madig** [comment]
Ok.

```py
from pathlib import Path

import vharfbuzz
from fontTools.ttLib import TTFont

font_path = Path(__file__).parent / "NotoSerifCJKjp-VF.ttf"
ttfont = TTFont(font_path)
text = "".join(chr(cp) for cp in ttfont.getBestCmap().keys())
font = vharfbuzz.Vharfbuzz(font_path)
buf = font.shape(text)
font.buf_to_svg(buf)
```

Font from https://github.com/googlefonts/noto-cjk/blob/main/Serif/Variable/TTF/NotoSerifCJKjp-VF.ttf.

main:

```
Benchmark 1: python .\bench\render_cjk.py
 x Current estimate: 637.132 s
```

This branch:

```
Benchmark 1: python .\bench\render_cjk.py
 - Current estimate: 582.391 s
```

Rendering all the CJK glyphs is so slow that I cancelled after getting my first estimate... I suppose this is a prime use case for py-spy and memray.

**Comment by madig** [comment]
Oh. It's because of all the string concatenation.

```
        for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
            pen = SVGPathPen(None)
            self.hbfont.draw_glyph_with_pen(info.codepoint, pen)
            glyph_path = pen.getCommands()
            dx, dy = pos.position[0], pos.position[1]
            p = (
                f'<path d="{glyph_path}" '
                + f' transform="translate({x_cursor+dx}, {y_cursor+dy})"/>\n'
            )
            paths.append(p)  # !
            x_cursor += pos.position[2]
            y_cursor += pos.position[3]

        svg = [ # !
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {x_cursor} {fullheight}" transform="matrix(1 0 0 -1 0 0)">',
            *paths,
            "</svg>",
            "",
        ]
        return "\n".join(svg) # !
```
Above + this branch:

```
Benchmark 1: python .\bench\render_cjk.py
 + Current estimate: 20.318 s
```

**Comment by madig** [comment]
Ok, your custom code in main is indeed faster now, once you use lists and join them later:

```
> hyperfine -m 2 "python .\bench\render_cjk.py"
Benchmark 1: python .\bench\render_cjk.py
  Time (mean ± σ):      7.917 s ±  0.045 s    [User: 0.005 s, System: 0.007 s]
  Range (min … max):    7.885 s …  7.949 s    2 runs
```

**Comment by madig** [comment]
It seems that most time is spent in SVGPen's `pointToString` function.

![grafik](https://user-images.githubusercontent.com/380829/178605714-4856c322-e01c-4729-b366-612fe94ef5e2.png)

**Comment by justvanrossum** [comment]
Would be interesting to compare with [uharfbuzz 0.30.0](https://github.com/harfbuzz/uharfbuzz/releases/tag/v0.30.0), as the `font.draw_glyph_with_pen()` method is [a bit faster](https://github.com/harfbuzz/uharfbuzz/pull/134) now.

**Comment by justvanrossum** [comment]
Or wait for the next release, as it's getting [a bit faster](https://github.com/harfbuzz/uharfbuzz/pull/135) still.

**Comment by simoncozens** [comment]
Right, I think we're going to use C and not Python for this.
